package ports

import "github.com/Hans-Einar/gh-tree/internal/application/api"

type PlanRole uint8

const (
	Executable PlanRole = iota + 1
	SequenceRoot
)

func (r PlanRole) Valid() bool { return r == Executable || r == SequenceRoot }

// PlanIssuer validates supplied immutable issuance data. Its lifetime and tokens
// must be generated by the native adapter. This value neither allocates entropy
// nor replaces Git's bounded, atomic issued/completed-step registry.
type PlanIssuer struct{ lifetime string }

func NewPlanIssuer(lifetime string) (PlanIssuer, error) {
	if lifetime == "" {
		return PlanIssuer{}, invalid("issuer lifetime")
	}
	return PlanIssuer{lifetime}, nil
}
func (v PlanIssuer) Valid() bool { return v.lifetime != "" }

type PlanSpec struct {
	Operation     api.OperationID
	Version       api.SourceVersion
	Token         string
	Group         string
	Step          uint32
	Role          PlanRole
	Summary       api.MutationPlanSummary
	SummaryDigest [32]byte
	Origin        api.Optional[PreparedGitPlan]
}
type planIdentity struct {
	issuer       string
	operation    api.OperationID
	kind         api.GitMutationKind
	version      api.SourceVersion
	token, group string
	step         uint32
	role         PlanRole
	summary      api.MutationPlanSummary
	digest       [32]byte
	rootToken    string
	rootVersion  api.SourceVersion
	rootKind     api.GitMutationKind
	rootDigest   [32]byte
}

func (p planIdentity) valid() bool {
	return p.issuer != "" && p.operation.Valid() && p.kind.Valid() && p.version.Valid() && p.token != "" && p.group != "" && p.role.Valid() && p.summary.Valid() && p.digest != [32]byte{} && p.rootToken != "" && p.rootVersion.Valid() && p.rootKind.Valid()
}
func (p planIdentity) same(q planIdentity) bool {
	return p.issuer == q.issuer && p.operation == q.operation && p.kind == q.kind && p.version == q.version && p.token == q.token && p.group == q.group && p.step == q.step && p.role == q.role && p.digest == q.digest && p.rootToken == q.rootToken && p.rootVersion == q.rootVersion && p.rootKind == q.rootKind && p.rootDigest == q.rootDigest
}
func (i PlanIssuer) issue(kind api.GitMutationKind, s PlanSpec) (planIdentity, error) {
	p := planIdentity{issuer: i.lifetime, operation: s.Operation, kind: kind, version: s.Version, token: s.Token, group: s.Group, step: s.Step, role: s.Role, summary: s.Summary, digest: s.SummaryDigest, rootToken: s.Token, rootVersion: s.Version, rootKind: kind, rootDigest: s.SummaryDigest}
	if !i.Valid() || !p.valid() {
		return planIdentity{}, invalid("plan specification")
	}
	summary := s.Summary.Data()
	if summary.OperationID != s.Operation || summary.Kind != kind || summary.PlanVersion != s.Version {
		return planIdentity{}, invalid("summary binding")
	}
	if origin, present := s.Origin.Value(); present {
		root, ok := identity(origin)
		if !ok || root.issuer != i.lifetime || root.role != SequenceRoot || root.operation != s.Operation || root.group != s.Group || s.Role != Executable || s.Step < 1 || s.Step > 2 {
			return planIdentity{}, invalid("origin binding")
		}
		allowed := root.kind == api.RetargetMutation && (s.Step == 1 && kind == api.StashMutation || s.Step == 2 && kind == api.RetargetMutation) || root.kind == api.StashMutation && kind == api.StashMutation || root.kind == api.CommitMutation && (s.Step == 1 && kind == api.StageMutation || s.Step == 2 && kind == api.CommitMutation)
		if !allowed {
			return planIdentity{}, invalid("continuation kind/order")
		}
		if v, ok := summary.OriginVersion.Value(); !ok || v != root.version {
			return planIdentity{}, invalid("summary origin")
		}
		original := root.summary.Data()
		if summary.Repository != original.Repository || summary.Worktree != original.Worktree {
			return planIdentity{}, invalid("derived summary subject")
		}
		if kind == api.RetargetMutation && summary.Target != original.Target {
			return planIdentity{}, invalid("derived summary target")
		}
		p.rootToken = root.token
		p.rootVersion = root.version
		p.rootKind = root.kind
		p.rootDigest = root.digest
	} else {
		if s.Step != 0 || summary.OriginVersion.Present() {
			return planIdentity{}, invalid("root step")
		}
		sequenceIntent := false
		switch kind {
		case api.CommitMutation:
			p, ok := summary.CommitIndexPolicy.Value()
			sequenceIntent = ok && p == api.ObservedStageAll
		case api.StashMutation:
			if intent, ok := summary.StashIntent.Value(); ok {
				_, sequenceIntent = intent.(api.PopStashIntent)
			}
		case api.RetargetMutation:
			for _, c := range summary.Choices {
				sequenceIntent = sequenceIntent || c == api.StashThenDeploy
			}
		}
		if sequenceIntent != (s.Role == SequenceRoot) {
			return planIdentity{}, invalid("plan role must match sequence intent")
		}
		if s.Role == SequenceRoot && kind != api.RetargetMutation && kind != api.StashMutation && kind != api.CommitMutation {
			return planIdentity{}, invalid("sequence root kind")
		}
		if s.Role == SequenceRoot {
			switch kind {
			case api.CommitMutation:
				policy, p := summary.CommitIndexPolicy.Value()
				if !p || policy != api.ObservedStageAll {
					return planIdentity{}, invalid("commit sequence intent")
				}
			case api.StashMutation:
				intent, p := summary.StashIntent.Value()
				if !p {
					return planIdentity{}, invalid("stash sequence intent")
				}
				if _, p := intent.(api.PopStashIntent); !p {
					return planIdentity{}, invalid("stash sequence requires pop")
				}
			case api.RetargetMutation:
				allowed := false
				for _, c := range summary.Choices {
					allowed = allowed || c == api.StashThenDeploy
				}
				if !allowed {
					return planIdentity{}, invalid("retarget sequence choice")
				}
			}
		}
	}
	return p, nil
}

// ValidateBinding checks exact portable identity. Registry admission, replay,
// release state, native issuer lifetime and actual success remain Git-owned.
func (i PlanIssuer) ValidateBinding(plan PreparedGitPlan, operation api.OperationID, kind api.GitMutationKind, version api.SourceVersion) error {
	p, ok := identity(plan)
	if !ok || p.issuer != i.lifetime || p.operation != operation || p.kind != kind || p.version != version {
		return invalid("plan issuer/operation/kind/version")
	}
	return nil
}
func PlanEqual(a, b PreparedGitPlan) bool {
	x, ok := identity(a)
	y, p := identity(b)
	return ok && p && x.same(y)
}
func PlanSummary(plan PreparedGitPlan) (api.MutationPlanSummary, error) {
	p, ok := identity(plan)
	if !ok {
		return api.MutationPlanSummary{}, invalid("plan")
	}
	return p.summary, nil
}
func PlanOperation(plan PreparedGitPlan) (api.OperationID, error) {
	p, ok := identity(plan)
	if !ok {
		return api.OperationID{}, invalid("plan")
	}
	return p.operation, nil
}
func PlanKind(plan PreparedGitPlan) (api.GitMutationKind, error) {
	p, ok := identity(plan)
	if !ok {
		return 0, invalid("plan")
	}
	return p.kind, nil
}
func PlanVersion(plan PreparedGitPlan) (api.SourceVersion, error) {
	p, ok := identity(plan)
	if !ok {
		return api.SourceVersion{}, invalid("plan")
	}
	return p.version, nil
}
func PlanExecutionRole(plan PreparedGitPlan) (PlanRole, error) {
	p, ok := identity(plan)
	if !ok {
		return 0, invalid("plan")
	}
	return p.role, nil
}

type GitMutationReceipt struct {
	plan                  planIdentity
	beforeAfter           []api.FacetVersion
	verified              bool
	cancellationRequested bool
	token                 string
}

func (i PlanIssuer) IssueReceipt(plan PreparedGitPlan, token string, versions []api.FacetVersion, verified, canceled bool) (GitMutationReceipt, error) {
	p, ok := identity(plan)
	if !ok || p.issuer != i.lifetime || p.role != Executable || token == "" {
		return GitMutationReceipt{}, invalid("receipt plan")
	}
	for _, v := range versions {
		if !v.Valid() {
			return GitMutationReceipt{}, invalid("receipt version")
		}
	}
	return GitMutationReceipt{p, copySlice(versions), verified, canceled, token}, nil
}
func (r GitMutationReceipt) Valid() bool {
	if !r.plan.valid() || r.plan.role != Executable || r.token == "" {
		return false
	}
	for _, v := range r.beforeAfter {
		if !v.Valid() {
			return false
		}
	}
	return true
}
func (r GitMutationReceipt) Versions() []api.FacetVersion { return copySlice(r.beforeAfter) }
func (r GitMutationReceipt) Operation() api.OperationID   { return r.plan.operation }
func (r GitMutationReceipt) Verified() bool               { return r.verified }
func (r GitMutationReceipt) CancellationRequested() bool  { return r.cancellationRequested }
func (r GitMutationReceipt) Step() uint32                 { return r.plan.step }
func (r GitMutationReceipt) Matches(plan PreparedGitPlan) bool {
	p, ok := identity(plan)
	return ok && r.Valid() && r.plan.same(p)
}
func copySlice[T any](v []T) []T {
	if v == nil {
		return nil
	}
	r := make([]T, len(v))
	copy(r, v)
	return r
}

type GitPrepareContext struct {
	operation   api.OperationID
	origin      api.Optional[PreparedGitPlan]
	predecessor api.Optional[GitMutationReceipt]
}

func NewGitPrepareContext(operation api.OperationID, origin api.Optional[PreparedGitPlan], predecessor api.Optional[GitMutationReceipt]) (GitPrepareContext, error) {
	if !operation.Valid() {
		return GitPrepareContext{}, invalid("prepare operation")
	}
	root, p := origin.Value()
	if !p && predecessor.Present() {
		return GitPrepareContext{}, invalid("predecessor without origin")
	}
	if p {
		r, ok := identity(root)
		if !ok || r.role != SequenceRoot || r.operation != operation {
			return GitPrepareContext{}, invalid("prepare origin")
		}
		if prior, has := predecessor.Value(); has {
			if !prior.Valid() || !prior.verified || prior.cancellationRequested || prior.plan.issuer != r.issuer || prior.plan.operation != operation || prior.plan.group != r.group || prior.plan.rootToken != r.token || prior.plan.rootVersion != r.version || prior.plan.step != 1 {
				return GitPrepareContext{}, invalid("prepare predecessor")
			}
		}
	}
	return GitPrepareContext{operation, origin, predecessor}, nil
}
func (v GitPrepareContext) Valid() bool {
	_, e := NewGitPrepareContext(v.operation, v.origin, v.predecessor)
	return e == nil
}
func (v GitPrepareContext) OperationID() api.OperationID                  { return v.operation }
func (v GitPrepareContext) OriginPlan() api.Optional[PreparedGitPlan]     { return v.origin }
func (v GitPrepareContext) Predecessor() api.Optional[GitMutationReceipt] { return v.predecessor }

type ApprovalIssuer struct{ lifetime string }

func NewApprovalIssuer(lifetime string) (ApprovalIssuer, error) {
	if lifetime == "" {
		return ApprovalIssuer{}, invalid("approval issuer")
	}
	return ApprovalIssuer{lifetime}, nil
}

type ExecutionApproval struct {
	issuer       string
	root         planIdentity
	choice       api.Choice
	confirmation api.Optional[api.ConfirmationID]
}

func (i ApprovalIssuer) Issue(root PreparedGitPlan, digest [32]byte, choice api.Choice, confirmation api.Optional[api.ConfirmationID]) (ExecutionApproval, error) {
	p, ok := identity(root)
	if i.lifetime == "" || !ok || p.step != 0 || digest != p.digest || !choice.Valid() || choice == api.Cancel {
		return ExecutionApproval{}, invalid("approval binding")
	}
	allowed := false
	for _, c := range p.summary.Data().Choices {
		allowed = allowed || c == choice
	}
	if !allowed {
		return ExecutionApproval{}, invalid("approval choice")
	}
	if p.summary.Data().ConfirmationRequired && !confirmation.Present() {
		return ExecutionApproval{}, invalid("required confirmation")
	}
	if c, p := confirmation.Value(); p && !c.Valid() {
		return ExecutionApproval{}, invalid("confirmation identity")
	}
	return ExecutionApproval{i.lifetime, p, choice, confirmation}, nil
}
func (a ExecutionApproval) Valid() bool {
	if a.issuer == "" || !a.root.valid() || !a.choice.Valid() || a.choice == api.Cancel {
		return false
	}
	if c, p := a.confirmation.Value(); p && !c.Valid() {
		return false
	}
	return true
}
func (a ExecutionApproval) ValidFor(plan PreparedGitPlan) bool {
	p, ok := identity(plan)
	return ok && a.Valid() && p.role == Executable && p.issuer == a.root.issuer && p.operation == a.root.operation && p.group == a.root.group && p.rootToken == a.root.token && p.rootVersion == a.root.version && p.rootKind == a.root.kind && p.rootDigest == a.root.digest
}
func (a ExecutionApproval) Choice() api.Choice                             { return a.choice }
func (a ExecutionApproval) Confirmation() api.Optional[api.ConfirmationID] { return a.confirmation }
func (i ApprovalIssuer) Issued(a ExecutionApproval) bool                   { return a.Valid() && a.issuer == i.lifetime }

type ExecutedGitMutation struct {
	facts   api.GitMutationResult
	receipt api.Optional[GitMutationReceipt]
}

func NewExecutedGitMutation(facts api.GitMutationResult, receipt api.Optional[GitMutationReceipt]) (ExecutedGitMutation, error) {
	if !facts.Valid() {
		return ExecutedGitMutation{}, invalid("execution facts")
	}
	if r, p := receipt.Value(); p {
		f := facts.Data()
		if !r.Valid() || r.plan.operation != f.Operation || r.plan.kind != f.Kind || r.plan.version != f.PlanVersion {
			return ExecutedGitMutation{}, invalid("execution receipt binding")
		}
		repo, worktree := facts.Subject()
		summary := r.plan.summary.Data()
		if repo.Valid() && repo != summary.Repository {
			return ExecutedGitMutation{}, invalid("receipt result repository")
		}
		if r.plan.kind != api.CreateMutation {
			if actual, p := worktree.Value(); p {
				if expected, p := summary.Worktree.Value(); p && actual != expected {
					return ExecutedGitMutation{}, invalid("receipt result worktree")
				}
			}
		}
		if r.plan.kind == api.PushMutation {
			binding, bp := summary.PushBinding.Value()
			destination, dp := summary.Branch.Value()
			if !bp || !dp {
				return ExecutedGitMutation{}, invalid("receipt push context")
			}
			if err := facts.ValidatePushBinding(binding, destination); err != nil {
				return ExecutedGitMutation{}, err
			}
		}
		if r.cancellationRequested != f.CancellationRequested {
			return ExecutedGitMutation{}, invalid("receipt cancellation fact")
		}
		if r.verified {
			switch f.Outcome.(type) {
			case api.RefusedMutation, api.PartialMutation, api.MutationIndeterminate, api.AppliedWithConflicts, api.StashCreatedCleanupRefused:
				return ExecutedGitMutation{}, invalid("unsuccessful continuation receipt")
			}
		}
	}
	return ExecutedGitMutation{facts, receipt}, nil
}
func (v ExecutedGitMutation) Valid() bool {
	_, e := NewExecutedGitMutation(v.facts, v.receipt)
	return e == nil
}
func (v ExecutedGitMutation) Facts() api.GitMutationResult              { return v.facts }
func (v ExecutedGitMutation) Receipt() api.Optional[GitMutationReceipt] { return v.receipt }
